export const fournisseursData = [
    {
      id:1,
      keyword:"simpfoc",
      name: "SIMPACT",
      email: "simpact.bk@simpact.tn ",
      tel: "+216 71 236 111",
      address: "Zone industrielle Jedaïda 1124 Jedaïda",
    },
    {
      id:2,
      keyword:"simpfoc",
      name: "FOCUS GRAPHIC",
      email: "contact.focusgraphics@gmail.com",
      tel: "+216 71 808 628",
      address: "45, Rue 8601 – Z.I La Charguia I , 2035 Tunis Carthage",
    },
    {
      id:3,
      keyword:"xlduo",
      name: "XL PRINT",
      email: "reception@graphianet.com",
      tel: "+216 71 808 628",
      address: "45, Rue 8601 2035 TUNIS CARTHAGE ARIANA",
    },
    {
      id:4,
      keyword:"skyflag",
      name: "SKYFLAG",
      email: "commercial@skyflags.tn",
      tel: "+216 26 209 151",
      address: "KM10 GP1-Ez zahra-Tunisie",
    },
    {
      id:5,
      keyword:"xlduo",
      name: "DUO MAGHREB",
      email: "dp@duomaghreb.com",
      tel: "+216 26 209 151",
      address: "KM10 GP1-Ez zahra-Tunisie",
    },
    {
      id:6,
      keyword:"sbcd",
      name: "SBCD",
      email: "commercial@sbcd-tn.com",
      tel: "+216 26 209 151",
      address: "KM10 GP1-Ez zahra-Tunisie",
    },
    {
      id:7,
      keyword:"sbcd",
      name: "Magma",
      email: "contact@magma-studio.tn",
      tel: "+216 26 209 151",
      address: "KM10 GP1-Ez zahra-Tunisie",
    },
    
  ];